// scripts/view-artifacts.ts
// This script demonstrates how to view the ABI and Bytecode generated by Hardhat compilation

import { readFileSync } from "fs";
import { join } from "path";

async function main() {
  console.log("📦 Viewing Counter contract compilation artifacts (Artifacts)\n");
  
  // Hardhat compiled file location
  const artifactPath = join(process.cwd(), "artifacts/contracts/Counter.sol/Counter.json");
  
  try {
    // Read the compiled JSON file
    const artifact = JSON.parse(readFileSync(artifactPath, "utf-8"));
    
    console.log("✅ Successfully read compilation artifact file");
    console.log("📁 File path:", artifactPath);
    console.log("\n" + "=".repeat(60));
    
    // Display contract basic information
    console.log("\n📋 Contract Information:");
    console.log("   Contract Name:", artifact.contractName);
    console.log("   Source File:", artifact.sourceName);
    
    // Display ABI
    console.log("\n📝 ABI (Application Binary Interface):");
    console.log("   This is the contract interface definition, containing all function, event, and state variable signatures");
    console.log("   Total of", artifact.abi.length, "entries");
    console.log("\n   Complete ABI:");
    console.log(JSON.stringify(artifact.abi, null, 2));
    
    // Display Bytecode
    console.log("\n" + "=".repeat(60));
    console.log("\n🔷 Bytecode (Deployment Bytecode):");
    console.log("   This is the complete bytecode used to deploy the contract");
    console.log("   Length:", artifact.bytecode.length, "characters");
    console.log("   First 100 characters:", artifact.bytecode.substring(0, 100) + "...");
    console.log("   Complete Bytecode:");
    console.log(artifact.bytecode);
    
    // Display Deployed Bytecode
    console.log("\n" + "=".repeat(60));
    console.log("\n🔹 Deployed Bytecode:");
    console.log("   This is the runtime bytecode after deployment to the chain (does not include constructor)");
    console.log("   Length:", artifact.deployedBytecode.length, "characters");
    console.log("   First 100 characters:", artifact.deployedBytecode.substring(0, 100) + "...");
    console.log("   Complete Deployed Bytecode:");
    console.log(artifact.deployedBytecode);
    
    // Display function selectors (extracted from ABI)
    console.log("\n" + "=".repeat(60));
    console.log("\n🎯 Function List:");
    artifact.abi.forEach((item: any, index: number) => {
      if (item.type === "function") {
        const inputs = item.inputs?.map((i: any) => i.type).join(", ") || "";
        console.log(`   ${index + 1}. ${item.name}(${inputs})`);
      } else if (item.type === "event") {
        console.log(`   ${index + 1}. [Event] ${item.name}`);
      }
    });
    
    console.log("\n" + "=".repeat(60));
    console.log("\n💡 Notes:");
    console.log("   - Hardhat will automatically compile contracts when running the following commands:");
    console.log("     • npx hardhat run <script>");
    console.log("     • npx hardhat test");
    console.log("     • npx hardhat compile (manual compilation)");
    console.log("\n   - Compiled files are saved in the artifacts/ directory");
    console.log("\n   - ABI is used to interact with contracts (calling functions, reading state)");
    console.log("\n   - Bytecode is used to deploy contracts to the blockchain");
    
  } catch (error: any) {
    console.error("❌ Error:", error.message);
    console.error("\nPossible causes:");
    console.error("1. Contract has not been compiled yet, please run: npx hardhat compile");
    console.error("2. File path is incorrect");
    console.error("3. artifacts directory does not exist");
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Execution failed:", error);
    process.exit(1);
  });
